name: Weekly TikTok Scraper

on:
  schedule:
    - cron: '0 10 * * 0'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup credentials
        if: ${{ secrets.GOOGLE_CREDENTIALS_JSON != '' }}
        run: echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      - name: Run scraper
        run: python impulse-analyzer/main.py
